[features]
seeds = true
skip-lint = false
[programs.localnet]
anchor_nft_staking = "BnbQDatiZBxcUxujTso24U3CURd6sTzbq1XRVCwghKXX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/drou/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
